import enum,uuid
from datetime import datetime,timezone
from sqlalchemy import Boolean,DateTime,Enum,Float,ForeignKey,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column,relationship
from app.db.session import Base
def uid(): return str(uuid.uuid4())
def now(): return datetime.now(timezone.utc)
class ProjectStatus(str,enum.Enum):
 UPLOADED="UPLOADED"; PARSING="PARSING"; SCRIPT_PARSED="SCRIPT_PARSED"; GLOBAL_ANALYSIS="GLOBAL_ANALYSIS"; GLOBAL_ASSETS_PLANNED="GLOBAL_ASSETS_PLANNED"; GLOBAL_ASSETS_GENERATING="GLOBAL_ASSETS_GENERATING"; GLOBAL_ASSETS_READY="GLOBAL_ASSETS_READY"; EPISODES_GENERATING="EPISODES_GENERATING"; COMPLETED="COMPLETED"; FAILED="FAILED"
class EpisodeStatus(str,enum.Enum):
 WAITING="WAITING"; PLANNING="PLANNING"; STORYBOARD_GENERATING="STORYBOARD_GENERATING"; PROMPT_GENERATING="PROMPT_GENERATING"; PROMPT_VALIDATING="PROMPT_VALIDATING"; READY_FOR_VIDEO="READY_FOR_VIDEO"; VIDEO_GENERATING="VIDEO_GENERATING"; COMPOSITING="COMPOSITING"; COMPLETED="COMPLETED"; FAILED="FAILED"
class ShotStatus(str,enum.Enum):
 WAITING="WAITING"; PROMPT_READY="PROMPT_READY"; SUBMITTING="SUBMITTING"; QUEUED="QUEUED"; RUNNING="RUNNING"; SUCCEEDED="SUCCEEDED"; DOWNLOADED="DOWNLOADED"; FAILED="FAILED"
class Project(Base):
 __tablename__="projects"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); name:Mapped[str]=mapped_column(String(255)); status:Mapped[ProjectStatus]=mapped_column(Enum(ProjectStatus),default=ProjectStatus.UPLOADED); original_filename:Mapped[str|None]=mapped_column(String(255),nullable=True); script_path:Mapped[str|None]=mapped_column(Text,nullable=True); script_text:Mapped[str|None]=mapped_column(Text,nullable=True); target_model:Mapped[str|None]=mapped_column(String(100),nullable=True); aspect_ratio:Mapped[str]=mapped_column(String(20),default="9:16"); style:Mapped[str|None]=mapped_column(String(255),nullable=True); language:Mapped[str]=mapped_column(String(20),default="zh-CN"); is_paused:Mapped[bool]=mapped_column(Boolean,default=False); error_message:Mapped[str|None]=mapped_column(Text,nullable=True); settings:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now)
 episodes=relationship("Episode",back_populates="project",cascade="all, delete-orphan"); assets=relationship("Asset",back_populates="project",cascade="all, delete-orphan")
class Episode(Base):
 __tablename__="episodes"; __table_args__=(UniqueConstraint("project_id","episode_number"),)
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); project_id:Mapped[str]=mapped_column(ForeignKey("projects.id",ondelete="CASCADE")); episode_number:Mapped[int]=mapped_column(Integer); title:Mapped[str]=mapped_column(String(255)); raw_script:Mapped[str]=mapped_column(Text); normalized_script:Mapped[str|None]=mapped_column(Text,nullable=True); status:Mapped[EpisodeStatus]=mapped_column(Enum(EpisodeStatus),default=EpisodeStatus.WAITING); storyboard_json:Mapped[dict|None]=mapped_column(JSON,nullable=True); prompt_document_path:Mapped[str|None]=mapped_column(Text,nullable=True); final_video_path:Mapped[str|None]=mapped_column(Text,nullable=True); duration:Mapped[float|None]=mapped_column(Float,nullable=True); error_message:Mapped[str|None]=mapped_column(Text,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now)
 project=relationship("Project",back_populates="episodes"); shots=relationship("Shot",back_populates="episode",cascade="all, delete-orphan")
class Character(Base):
 __tablename__="characters"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); project_id:Mapped[str]=mapped_column(ForeignKey("projects.id",ondelete="CASCADE")); code:Mapped[str]=mapped_column(String(30)); name:Mapped[str]=mapped_column(String(255)); description:Mapped[str|None]=mapped_column(Text); appearance_json:Mapped[dict]=mapped_column(JSON,default=dict); costume_json:Mapped[dict]=mapped_column(JSON,default=dict); importance:Mapped[str]=mapped_column(String(2),default="A"); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Scene(Base):
 __tablename__="scenes"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); project_id:Mapped[str]=mapped_column(ForeignKey("projects.id",ondelete="CASCADE")); code:Mapped[str]=mapped_column(String(30)); name:Mapped[str]=mapped_column(String(255)); description:Mapped[str|None]=mapped_column(Text); spatial_json:Mapped[dict]=mapped_column(JSON,default=dict); importance:Mapped[str]=mapped_column(String(2),default="A")
class Prop(Base):
 __tablename__="props"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); project_id:Mapped[str]=mapped_column(ForeignKey("projects.id",ondelete="CASCADE")); code:Mapped[str]=mapped_column(String(30)); name:Mapped[str]=mapped_column(String(255)); description:Mapped[str|None]=mapped_column(Text); importance:Mapped[str]=mapped_column(String(2),default="B")
class Asset(Base):
 __tablename__="assets"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); project_id:Mapped[str]=mapped_column(ForeignKey("projects.id",ondelete="CASCADE")); asset_type:Mapped[str]=mapped_column(String(50)); entity_type:Mapped[str]=mapped_column(String(50)); entity_id:Mapped[str|None]=mapped_column(String(36),nullable=True); asset_code:Mapped[str]=mapped_column(String(100)); prompt:Mapped[str]=mapped_column(Text); provider:Mapped[str]=mapped_column(String(50),default="mock"); provider_task_id:Mapped[str|None]=mapped_column(String(255),nullable=True); status:Mapped[str]=mapped_column(String(30),default="LOCKED"); file_path:Mapped[str|None]=mapped_column(Text,nullable=True); public_url:Mapped[str|None]=mapped_column(Text,nullable=True); metadata_json:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); project=relationship("Project",back_populates="assets")
class Shot(Base):
 __tablename__="shots"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); episode_id:Mapped[str]=mapped_column(ForeignKey("episodes.id",ondelete="CASCADE")); shot_number:Mapped[int]=mapped_column(Integer); shot_code:Mapped[str]=mapped_column(String(50)); duration:Mapped[int]=mapped_column(Integer,default=2); scene_id:Mapped[str|None]=mapped_column(String(36),nullable=True); prompt:Mapped[str]=mapped_column(Text,default=""); negative_prompt:Mapped[str|None]=mapped_column(Text,nullable=True); camera:Mapped[dict]=mapped_column(JSON,default=dict); dialogue_json:Mapped[list]=mapped_column(JSON,default=list); references_json:Mapped[list]=mapped_column(JSON,default=list); status:Mapped[ShotStatus]=mapped_column(Enum(ShotStatus),default=ShotStatus.WAITING); video_provider:Mapped[str]=mapped_column(String(50),default="mock"); provider_task_id:Mapped[str|None]=mapped_column(String(255),nullable=True); video_url:Mapped[str|None]=mapped_column(Text,nullable=True); local_video_path:Mapped[str|None]=mapped_column(Text,nullable=True); error_message:Mapped[str|None]=mapped_column(Text,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now); episode=relationship("Episode",back_populates="shots")
class GenerationTask(Base):
 __tablename__="generation_tasks"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); project_id:Mapped[str]=mapped_column(ForeignKey("projects.id",ondelete="CASCADE")); episode_id:Mapped[str|None]=mapped_column(String(36),nullable=True); shot_id:Mapped[str|None]=mapped_column(String(36),nullable=True); task_type:Mapped[str]=mapped_column(String(80)); provider:Mapped[str]=mapped_column(String(50)); provider_task_id:Mapped[str|None]=mapped_column(String(255),nullable=True); status:Mapped[str]=mapped_column(String(30),default="QUEUED"); request_json:Mapped[dict]=mapped_column(JSON,default=dict); response_json:Mapped[dict]=mapped_column(JSON,default=dict); retry_count:Mapped[int]=mapped_column(Integer,default=0); max_retries:Mapped[int]=mapped_column(Integer,default=2); error_message:Mapped[str|None]=mapped_column(Text,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now)
